hash-format = "sha256"

[[files]]
file = "mods/amendments.pw.toml"
hash = "5a53be204efcb61ed865b934d60f0ed29fa74d02ebecb1276f668d6baa57e40b"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "74bbdad7434bc02ec767c15c0136269f885331601f73fa2365252c24e58c09bd"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/astikorcarts-redux.pw.toml"
hash = "c3daae892d91d5b36c65fbd18f19d22a61fcac210f25350cde0a413c6a49210f"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "49ef0b29b650084f38aac8faf1537b966f1c976029b1df48bb72a614c35a9641"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7a266a082b54627e5f95aa154871114fded8c0a06af104e49cf08668b869cfad"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "1b31cb793a692d9f692b233eab37e6fed156f7b05c4a2080a75ea6c06c38c178"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "52b4f29eb4a4392ef085617292842dc9fc84d86c318da5ce470b24eab77f6bdc"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "58396d4cd2dee0f75cf56def0ab301021b6e09a83bd2564212152f0a73433568"
metafile = true

[[files]]
file = "mods/biome_particle_weather.pw.toml"
hash = "aa6715786b7020b5508a1f39aa49a32645b708b305461a0d97813782cf360a3d"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "450686274e074a0caa8adb5ae1a740abb37126cbe02df4a7aa29b54532c0aa79"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "8a8ea0af79b88d9c192d208aa5be4bacd934e2b92d4721566e2e796eb9761e10"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "a23cdef520412ed5bfebcfa6d6bc04d90f00a6836318d74d79ca4ffc940be9be"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "14481081a9e233f4ba57df8a77ce028184818143eae1c73b60749ea482c912e9"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "a613f5d2df911fea606968bbdb56eebfd05ac02ada846cf0d2e56e72345d9338"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "94615e505b64b850d3df7b50c292407a3b2f327ed1989c4e7d2907bb79785cde"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "e271d3f6a204153ea55370a2fab28e6ed329ab020d05fc9b03a5163065384dec"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
hash = "2ec895f34f33ad639dc6e9781c5450e7eeff746ea932d0309c6786f7ccda70e0"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "0e17f9758f6f67ef87aa6f8d5afc47901521a05904cd8470ef65063b48e69d73"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "903352ffbd84d4b95fed905893f4715d9c3f88ec9fff6fb06f6e359e0b839dc3"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
hash = "c6266e6abc3eb46a62db3d106a915c78d8bd40502e45c23c729bad7e21de1141"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
hash = "1d2d4cdfb2ff8f6b9894d63bdced20e1ad3673a753cad8bf5fe0c60d6acd5a27"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "2fba2317a375669ccb1376525d4d4e0d1903cc5dc44fc70dce1d0e3dbb6aacb1"
metafile = true

[[files]]
file = "mods/crawl-on-demand.pw.toml"
hash = "a40842f88b0d835102353c9786207d234da829c311675ac1d2c73959e088aea9"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87be52b8aaa9864eab1ec2df8c862cd01a084989b07c4cdbfaa21c57a9a778a6"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "5391ac307bbc73edb72e7eb11495af96e327eff1c02ff67d2ebbe615ca6766d7"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/cryonicconfig.pw.toml"
hash = "6dafd9732de5f9c11f6e4293d4c600d2564b5879392aa2d046dad8b01c08c483"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "31bec9d75cc9e7e00e3b564c7ad5ff161840a7f5d2a6e39e6ba4672b15ed2040"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c5ea75feae4d340856611f78a29e6f1f0b7e707bfe43847f11d25fac1769dee7"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "53fd334af7b7c6ada2b3d15a8d666011c5b54bcfc5515e6ca2d13eeb3c286b0d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a4c814876cd9046f9cdbe0a5967edff092adb8c28de2d717ce5fe469d6fbc9a2"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "4f5b3c3bbd6b74b91d0d6a8073e8596a68f181c7a75c670d7bddba8716fbe561"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "b819114773db1e86fa897907d79abf9925f05a6ae3fd10f7a02cca41f3e9a0d2"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "f0b4372343e873512d57e5ee877f37362f8dde8e75771075abe44686509294b9"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3b5b7d833a2dd0a0064371036ab1da338cbbf82fb42d84dc8078dc9f48a3b63c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "628d5006156ef76351266ad03267b573b9b9f3777b105caee67ce18bbc410146"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "c7dfdcddf32a63084e0b54679e33378769bc4f48bd97f006008405da5e6df2ba"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "36c887897d3e8781cc93f79932ae78d7c5f8a1936d76b158cbcc4af0d47ea68d"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "c3855a5011cc263726532999f35c8691db9fa60b9d470758dd826d25c29ed4cb"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "8a2ebaa5e91514420178322fd4c3c200d095618269073a0d44a17f0287747adc"
metafile = true

[[files]]
file = "mods/fusion.pw.toml"
hash = "9c94815c028b18cd04c63b604209be515d209dff8f4bc9960867da0b13a0dfe8"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "1030e18f2e875dfdf39de82b823e1dfe6009f21f1aaad338137d3a90504e2f7e"
metafile = true

[[files]]
file = "mods/gml.pw.toml"
hash = "e3e2dcaf45321da0664bac70e625520b19c3bcb61033b716fc5584121fe8abf1"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "c52fd46a68f495149305e4cad4a6c3961d5875448b69aeff8115845899aec7fd"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "3d5d71177f4b6fe0615e638dbbbbfae2b41cd44c128c65e0a2139eb5e9236165"
metafile = true

[[files]]
file = "mods/inventory-sorter-configurable.pw.toml"
hash = "15737439a8dbfff1c2bd5e89b89e31681faf8d0629edfa9b890021b7cec8367e"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "63e85a58d176a1efff3ca84d9ad90d3e10d5adc86d9b90b13915b25c0bc180b8"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "583428d127b24cd72904f4f10a4dc2693286dc92da2fcc922c60fb05d3c7b9dc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6b7b35db4ccf235d771504c313fb2897139c2f8f8b8857d9b00b97b5b9d624d8"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "b684e31e68e4f0fe7a418afbdc2318a044d208ffdd9b19ea9d4f0ab918536efd"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "66bcfe786e6bbdee6f7ea0805ec3d2561b41285a5c77f1e465e80f4c2fd9200c"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ee387ba74c2c7e999d48071408abbd1ca322e70f36e79c590a150c9572d3a9cb"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "adb67ada5c165ea4a43f4c3e53ffd61c90e21292596b5609d97e938f6e8e7b16"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "426fd37ec95797af16797632e70c63436ca12719c0adb16ffca931970a411ee2"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "0a9814fc1e89d6fc86fb237fa7a97cb8f5e48c0fcab200035102e45f9b681516"
metafile = true

[[files]]
file = "mods/minecraftcapes.pw.toml"
hash = "2564a2a65b242f1bdd699a21d94dfced5698a451b45b57382433cb94e0f06e2f"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "ab170eabaeec3e80c59e850a7d8aee32edfffd6a1e40e2c2f44575c69d122054"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "186909f73870979511db893fca2e2a318b311361f168d425ba0e58fc539188ee"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "8dd17f19e28b517c1ce56a2024ece8a37ca9bc866079d23969cc3811577861a4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/moving-elevators.pw.toml"
hash = "7750a6abebdbb69ee589c3d80befc76c57a9c611d593d1447572f4cf168c3df3"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "b82b347b9ea6da764ee271e5a1bf208f146cb5d69b9a86c045f8d99179aeb983"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "362ead0883974a7de4dd711a75ccfe71b2ceadf172211934e8cd6084977c0f49"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4c96dddf8b3d5bf5ea331459b13d23d7d37332dea2275c00ef755420a66676c4"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "acaf74883794f150634fbaf000e15098162610d2e1ef2d4029a64c7b0fe71e6e"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "aed7f8cfd6f50c5a0c3209907e3b615242e77ddcf5652610a81511c752fec3f1"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "55c6d0b8ee25fd6a37a964805de3d2eab3f20d73a88ba77a63b4a51fd985d9dd"
metafile = true

[[files]]
file = "mods/physicsmod.pw.toml"
hash = "5a76163e646422ba6e3ff74595a17a5bc21cad00504448d085571986de49078b"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "c3f63fc5f823fe29561fbbc9deb3957d991fb9331c62a5ae27ec3cad6b1265a7"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "765987a78e5d8c782d0da2de99998b43b5907d6c41347d3804045ad109e4a586"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/proxy-compatible-forge.pw.toml"
hash = "e6a43dc4800ba45f2971d3caf39d32f86bf747b5a86f3857036c75854e7f0c22"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "4dd7038889da90e145f9d074bec64a61aaae12dc57c875aa7ad99b8b2e07979b"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "8df897c0f7831e919aa528c3c1e5239f39439c123d99761230ab2357132bad98"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "2376fd9539b6b41c10117e81c166b16de416b1df530efee302e693c9de0a5fde"
metafile = true

[[files]]
file = "mods/realistic-bees.pw.toml"
hash = "b727e9c00cb3dcd25508b398c3f12a72a5c28d96b5119d4cc38f518a86f855d4"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "817b4a47826bd99c69957fe07131d5704984f89fec96287cdc20c6fbe46100cf"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/shoulder-surfing.pw.toml"
hash = "009796bfbb55cb4b666520dc8eaa1b6bfefa1e8f47f3ea04cc1a79932f42e1e0"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "8fed76ae3ed08f943570023892eb4680990198ca37ec8b24232b6237d8f7be29"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "748b3b816f78209b3966da7feda5193a7c7b34ecb9b43159a4a85f9657fe865b"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "dbc27d52da4f0cb8d58bd3b7a7a8608e3170feb9b5c128816a3731c2a2d2f8b3"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "2ad65cabd3df8b75491cfeb616dd7851238749aa29e1bbabeeabe1e5f72fd0d2"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "416bb6449da951ec1a04156348c502b9e47a947212becc173d277faaddaaaccd"
metafile = true

[[files]]
file = "mods/sounds.pw.toml"
hash = "4a603693baa20af56faea5e84e47d780b3ac961ead3ab8529e2dd54b42aefea4"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "af4417bb56dd861fc06eb882d999cc205a2b0222bd14c75a1a58eee3bae0e60b"
metafile = true

[[files]]
file = "mods/stack-refill.pw.toml"
hash = "d752b843672914045093b09d87f4e33f6b990638be3955d1a4da7bc8c97a0c71"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "1cf9cb3955b075664ea4fba13b47fe7160975740a28864983aebd53d39c1946e"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "b969799c17defc1e7c76e4605557c9d32802a0004a5e45b7044e85d3d9c43345"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3848bc11aa2acabef74eb85ca74b8ca8e23733b7fcbc77293165c5c7161e3288"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "23c3dddf24d8d65b2ad798247389647b47e10439dca2c46b1c958a8d2b0a1841"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "39f24d81cf381ff6a4ac2d58792e66c43a3d566b92bb644eaec86cc97f5b649e"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "6160cdcd8b686e90f72e76072ba96de7c5ae40460b3771401222ddebdee1d5ed"
metafile = true

[[files]]
file = "mods/travelers-backpack.pw.toml"
hash = "145a7f1c745cd5c58c9a9c667181a8daf2146d4f83eb86a6889d62512ffb9441"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "c88c91d6d3935671226bfbaf09090b6663cb6797f22fd4b5f0c9941362b0b226"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "073176bf34feab44656497b2e5ddf80eae8cf12f743f332d56ac0544bd91d8e2"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1a592e56f6720b44d1031d2d715d454eff2099e915160c0c75f853ae8b314b15"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7e7b7624e041a1364971057d1c47f2b74730e191f142b73aa50223f95978dd96"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "4bcf74d4569def60ca031d565350952c2edcc420f26278bc7997654a77b6fb4d"
metafile = true

[[files]]
file = "resourcepacks/clear-glass.pw.toml"
hash = "696097618b78aacf4abd48dd7c027108aab9391ee5d7b49d9f6297fca5c5440b"
metafile = true

[[files]]
file = "resourcepacks/entity-texture-features-translation.pw.toml"
hash = "d3383057e65db3ca479dbdc4a74ab3583760ae79e61b05edbb620ff9e053eec5"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "c35f41d09504478ac9d85d9a939460511c50676f5ea3a19537a2ac204281506e"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "42b8a59616b3ed15a02e55466dff7ab400d481a8730949ce0168a927b71b91fb"
metafile = true

[[files]]
file = "resourcepacks/fresh-moves.pw.toml"
hash = "d22bff8a4ecb807d779784716ad315466778d0457b0d734eeeb6ff7f5a296a3f"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "8ffd81a5e0b4c3bc2daf0d86714ef56df4beb1ed87a5c41c4e9bbb94a7006bc1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
