hash-format = "sha256"

[[files]]
file = "mods/ProxyPortal-1.0.0.jar"
hash = "f86ef81a89dd2b8f1b48d8173ccebabbcf829227e0a03cbaa899250984ff5400"

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "d4838d91cd7747816ade0f2f4a46c701a53c3ef84cb278ec24e8f6fb828a85c3"
metafile = true

[[files]]
file = "mods/analog.pw.toml"
hash = "a7f0850f3ae1c6e6f75126f67438af21d853a86b8b8d6c146cb61d47c6e824cf"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "a773df76089453f964bf196aae2d9e963d28fa18dde4e1a6ce9260206e6f033a"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "be28a9ff89c60140b2983eb91089e77bec90bc5a0379c25472be01cb14dcbb97"
metafile = true

[[files]]
file = "mods/biome-replacer.pw.toml"
hash = "6ed307a73da7ca52b03e143a87780732dbbc70d9417b4bcc04937f561564a807"
metafile = true

[[files]]
file = "mods/biome_particle_weather.pw.toml"
hash = "5248492ccdd394f46b34153b4b75ce25586d6242da13dc6935403552e97605ab"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/cameraoverhaul.pw.toml"
hash = "2617864bc12ee6926e1b9dbb455381fc348b6f62015eaaff5b5cc4b3523e9a9c"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "c899acdc322ab52800a6e305a16427297f411c1c39d97983be96e8b6a34e157c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2dda36229536c02155b8bdc705598904b74b3e958e56bf7946785f59c3427a9b"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "8792552849464a56b066435132a3563a81e1ed70afedcc8c9dd1da602cda1d5f"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "e5196147e561521c5a3ebaea601191e442d252cc8f0a7be8ba8db136f93c44fe"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/concentration.pw.toml"
hash = "75226fe31d286f478959036e3431292edacf7be2c51012a9dea5d74ff24ebec3"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
hash = "1d2d4cdfb2ff8f6b9894d63bdced20e1ad3673a753cad8bf5fe0c60d6acd5a27"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/cosy-critters.pw.toml"
hash = "452d8876c7868637e658a5ec99a6056706e50e468ca6238befc455d635f1dcfb"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
hash = "895602d01d010ba10c9662f61d382393cdc270ba02d7cd8fb0d95f5fc7768972"
metafile = true

[[files]]
file = "mods/crumbling-hearts.pw.toml"
hash = "1bffdfa1801c5a011971efb599dc8c61378cf9a45f69d6440224b4d19e2d9b30"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "23b3bf6d1931acd2aa6daa5409b274b0d4ec9ec659c01d11454093d8fcd1e342"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "24d6c27315866a6dd672daef2f844b1b202aa173953824cb3586bed8667f3d5c"
metafile = true

[[files]]
file = "mods/dynamicsurroundingsfabric.pw.toml"
hash = "6269a762579b50b12cb8150e3f304de168b091630605079b56427b68ebd795f0"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "cc46728d8879ff5ab1e00f17bb63bacaf30ea2699bb692c0ca5e084572ae3e8e"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "2a421f249e7022255938fafdebf4a9d6490d62aecbabd48a9e9a3e52aacd4d0b"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "ecc30c21290ac87a732085e16add94a392d4e5dfc0bae5f353975eea51a38a84"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4898b9beb1b7cf7df38346b02d9756c10e09408b6344e3295fe7177b25549f14"
metafile = true

[[files]]
file = "mods/entity-pin-cushions.pw.toml"
hash = "98fc45453fdac86d361d4d16736983534d93f1c4006bcece0502070d259126d4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "054628ed76bd95bde1dbb4343721f3fbed87c8ad798ce99fc74b1171c39b6400"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1824d1cc8f4f82a88972b9220dc6806c05968d651fb38f6bfe69e4d8215fc0ed"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
hash = "b9971aa45df874975e051c11291b040e0f325e3d36c4ee6e93f252fdf7c0ffc3"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7d61ad815f97afb27f7e97475e80376aa19fecf25a1b04a500a4c3a6e5055973"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "973cd98470fa91a57786bcf243f45f0daba9a035bba484f41dc1ee13636e9db2"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d8cdb69801ff0ffdf8c9cf6834dd592ca79ce1da139d303f8d17a62afec1abe2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/harvest.pw.toml"
hash = "078860bac1f307372efd36c5e861dd4fac7a387f138f09989f8fff0ad12b7904"
metafile = true

[[files]]
file = "mods/hold-my-items.pw.toml"
hash = "d82a9b3f9ba777fcfa871322fcc168745c28f9a8ea18032e4ed6f0a3d3d9c32a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/immersive-lanterns.pw.toml"
hash = "67073e76c80987fe6193fdb50f4db0991467ba3fa265829a132ca878e5261c0a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5f694b0c16bfbf69b05cb28eef7a553ae548e623bc2cbccc98e01d950d3611db"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e40ab1a8992d800199a6ac5a1a7411bae8141817f645c82c1fdc8c1381393f9e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "33b394f6cf1849a124b2021a56b29455e2fcb2c5a3a56901fe8ad0dbf3d4c6ee"
metafile = true

[[files]]
file = "mods/mariums-soulslike-weaponry.pw.toml"
hash = "8e3e81260ef8959aa97a1bb32f2cf83001782506da2e27f40e56124f6a5c9796"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c04b43e6c95e18c7310c97e47b3e5bcf65c23180a899a85c97d9fa8f5f773c98"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "230b1f5cd118accacf41f268e122bd420420d9e5248d43513090804739a832f3"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "f53b91397b8a969e843af8772db448ab1c9bc556233a3b26266c52cfa77950fe"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7d5af9f25bc04dd33ec6e55983f7c660d0802461ecad3b5a820dd05dfcef2f70"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "467cff2b82577836e3fde8365c2d354e2ecaee348d3e86dd1b8ce87be543befc"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "1e2b3c4d14e7eb437ce71ceca81b54e345252dcd8d4e6533bf259ea7c7491302"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "5e527159dd30ddd4c68c2d363b4e973ac60a65a260b41f5d7a8ac2ab94be3e30"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/particle-interactions.pw.toml"
hash = "6a085c05e1c4f0712bf68d60cd3ed4d658e87e6fd186caaf380015ece32eaf57"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "6e454809d22c0967ace0a59408260da91ce80757d00eaa4720f0496fcd1fddd1"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "9bceeadea46405d869a5b781efb109ac9fd7b4455c9c536092ccc93a135bad96"
metafile = true

[[files]]
file = "mods/perception.pw.toml"
hash = "b2070f49d5207fe0ecd80bd78f4c638661f63b7f495560f2919f5a5308135b9c"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/player-animation-library.pw.toml"
hash = "a8dbb5dfe3d0be23d628ae89c805c50de83db89e382c573e37695ec20f246de7"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "ae55eda5b79aeb01fd4068cc34051019e34779c2d4748aba86e5dba522b7b61d"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8a64fdd5384cd26c91475a423f3bec24dd4d98796df7683a5070ef105d421ba4"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/proxyportal.pw.toml"
hash = "911f15a10bddcae1baf2be7b7b7d829ce5634f85bbcb204298a925958fc92463"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/ranged-weapon-api.pw.toml"
hash = "1169c6f5f7cd13d01081f996cda2a029809877aff999e9bf4e6b0d44b027aa58"
metafile = true

[[files]]
file = "mods/realistic-bees.pw.toml"
hash = "c2e9b7324f1bdc58a32843a32d6ccc8b000119335a6aabf4c59dab0d3ee1c397"
metafile = true

[[files]]
file = "mods/reflex-antilag.pw.toml"
hash = "297023a515ae4b77ce7835df3e30c040a2c24bcb8eb7af2114d28a7d249012a6"
metafile = true

[[files]]
file = "mods/resquake.pw.toml"
hash = "e60b826b911f5c486e18ad9b76ff1a585269692eda5b790167b678d4f19a3f00"
metafile = true

[[files]]
file = "mods/serious-player-animations.pw.toml"
hash = "9a1a1c0537a49c74bdb401b214ecd4ef1f8956b8317b6f13b04abdf940b3a0d5"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "6cc085cf33f5753a3c02f5af70d1224c675e84bdde8372850c9157569622566c"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c8bda7e40ba3e14e7e78d1c1f80be842eb6d0acd21fca7b2e6a962bc810b9e46"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "272b27d64cd27b909567437683287909b35de9f78db27214efb1d5e4334f9f82"
metafile = true

[[files]]
file = "mods/sitting+.pw.toml"
hash = "6849cbe791205308a6cb7e6d06172dca663446f7c6573ee2ce10f537aef9f16a"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "6475037d680289b4cf8bca4e375b3ecb9c9d6d90dd785b9bd085a42b9c84b795"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "ea42c8cd33e92216bac99e999fd9d2e1e037dd1a695ed5e7e05c640fd3ee35d8"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "6c6b69bf2bca3b3a8420688391124aa90d24e235b98ee01097f03f0fbf22d9cb"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "7d47e3d8bee4711ab37491e5e91bad186b6606ba560ab8a1dec753c157cf1151"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "39426bfeeab22ea17f94fd3904dd9b78f9a3c9b4ddcb732b734ddbfd0e3568af"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
hash = "f47b75ab81d6334bf93962de5537a7889a80ac587a833cf582262b8694b135b0"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "33122c36e3a43deb6550a425ad01fa434e9964b2bbfd306743e021fb94a4de5c"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8f391603f2b1aaf63717c180e82635b7cd2d57617c02edac60f9d25244731df1"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "58eb7f330c8e2158385fda1a391b1a93faf36459f8d25ccb482e26ce885deb5e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true

[[files]]
file = "resourcepacks/entity-texture-features-translation.pw.toml"
hash = "d3383057e65db3ca479dbdc4a74ab3583760ae79e61b05edbb620ff9e053eec5"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "c35f41d09504478ac9d85d9a939460511c50676f5ea3a19537a2ac204281506e"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "42b8a59616b3ed15a02e55466dff7ab400d481a8730949ce0168a927b71b91fb"
metafile = true

[[files]]
file = "shaderpacks/bliss-shader.pw.toml"
hash = "8ffd81a5e0b4c3bc2daf0d86714ef56df4beb1ed87a5c41c4e9bbb94a7006bc1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
