name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5460e1b09a7f8eb0074e37f1e195652416f5f4a6cbad0cf866c794c5386f5ad"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
