name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1b184ac2a5e900397c58bd199fe060a9227520a6556fc150499e2f61c401e3"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
