name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd0d3d22ef9bcc2d6aec379c22faaf864dff909e0779ac6970a4c228c0bd4677"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
