name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4d2c2f7473a455a05630056ecbf3770fe0b1968abf0d42ac35707f2e3e54e56"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
