name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5147dd7cd9c42181823bb04f62ef8a5883505c33fbe228ae4f06ca62d2ead60a"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
