name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21417d147bf1b34c6130af7982a051d1ee6aee4dabd2264ef73c7ddbb0904d41"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
