name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3bf664c98615a586a98a7a39bef10edf443682deb63a9088ee2f731ed38ff6a"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
