name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1679151a1ba2c2c2c1af233971bc119be8dd2d2e570bace4e34b87e27ef8eb39"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
