name = "Noahs-Server-Ultra"
author = "Noah"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0c86f455c09bc575227f9fab89d63ae79284424a7f3490cfdc445ed988a8152"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
