name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd8f286abb099d899574df622ee8059d7a96f2cb49023c93a9ebcb53133fde5"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
