name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b69ed4fd5e5757398c1d14846c88d7ac3a2a956572f08269d8ed72e410f109a1"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
