name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4b66bc3aed9f5012cfae134d059f3436fabf9390e8429f18d4e2f245a78772d"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
