name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4793588a41ccbef3e04a7f036dae6c85c6219341fa58bb48afa73a811444ac2b"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
