name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bceb8843edc3dfef9849424529c453dbed705b46a34f9232de5c0b6748d0161c"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
