name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b720d330ac3a7afe374dd4c77004692d68344bfbb0405b8ef82c68cc368e440e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
