name = "Noahs-Server-Ultra"
author = "Noah"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6247d8566bd8c5039f5d23307070a7c59f015ed62f79ef3b3051156c68c633"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
