name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f96f6b5eff565887ba4ea2e56af531f3fd14ef80f792bc7370a293107a050843"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
