name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a95462390dc5aa19ddfd81eada0f1df1ac4a6124610e8d1fa86da382863f680"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
