name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a736d825f460b13090dc9c0889ce85abe827696405af9b21a20dc80692fdd53"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
