name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d747f99c5174dbae1107c1a6c13016a798e4373d25390681fb12a54135c058b4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
