name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c68e86e4e4cda2fb0985ec8c0f19f1e65fa7bcc78af9a5d336309f598e69dd9"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
