name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e85bbf100d03a5577290d63eee000b76ed0b9a2dc48fbfbfeb072e7d0764de8"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
