name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c5733b9282d28da47c989dabdfb9d02c3f704e329dffe215bfdbd35eb890b77"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
