name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "223af2e1e066159de193f9478f8856b037a96c5633b2c355e44de41ed01036a4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
