name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a06266d33fb7a3c8e55e8f4eeafa90d9789729411ab6dbbe27f0a3d14d7a14b0"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
