name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a5f991cc4bb957a3fa8329238fe488d66df70f43bfd0dd9f4839269ea6da9b"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
