name = "Noahs-Server-Ultra"
author = "Noah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6e4b5ff75567dd78ce5d3875315632170e33c289c29b2af77c44df97ab6a405"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
